# docker-compose.yml文件的版本
version: "3"
# 管理的服务
services:
  master:
    # 指定镜像
    image: redis:5
    container_name: redis-master
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - "./conf/master.conf:/usr/local/etc/redis/redis.conf"
      - "./data:/data"
    command:
      # 执行的命令
      redis-server /usr/local/etc/redis/redis.conf
  slave1:
    image: redis:5
    container_name: redis-slave-1
    ports:
      - 6380:6379
    volumes:
      # 目录映射
      - "./conf/slave1.conf:/usr/local/etc/redis/redis.conf"
      - "./data/slave1:/data"
    command: redis-server /usr/local/etc/redis/redis.conf
    

  slave2:
    image: redis:5
    container_name: redis-slave-2
    ports:
      - 6381:6379
    volumes:
      # 目录映射
      - "./conf/slave2.conf:/usr/local/etc/redis/redis.conf"
      - "./data/slave2:/data"
    command: redis-server /usr/local/etc/redis/redis.conf