version: '3'
services:
  mysql_master:
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=mydb"
    container_name: "mysql_master"
    restart: "always"
    ports:
      - 3307:3306
    volumes:
      - ./config/master/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./data/master:/var/lib/mysql
    networks:
      - overlay

  mysql_slave:
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=mydb"
    container_name: "mysql_slave"
    restart: "always"
    ports:
      - 3308:3306
    depends_on:
      - mysql_master
    volumes:
      - ./config/slave1/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./data/slave1:/var/lib/mysql
    networks:
      - overlay

  mysql_slave2:
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=mydb"
    container_name: "mysql_slave2"
    restart: "always"
    ports:
      - 3309:3306
    depends_on:
      - mysql_master
    volumes:
      - ./config/slave2/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./data/slave2:/var/lib/mysql
    networks:
      - overlay

networks:
  overlay: