# docker-compose.yml文件的版本
version: "3"
# 管理的服务
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
    environment:
      # 环境变量
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}