db:
  restart: always
  image: postgres:9.6.2
  #解决权限
  privileged: true
  ports:
    - 5432:5432
  environment:
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    PGDATA: /var/lib/postgresql/data/pgdata 
  volumes:
    - ./data:/var/lib/postgresql/data/pgdata 